keys:
  - &users:
    - &mario 2080983ce6822c29c09f8d5ebac570b2172822a3
  - &hosts:
    - &quietfrost age1ryaeqtrxtp3u5ku78wqlcxrn7vp3zuknhuwykt2ps6hh5ck2taqqqxlj49
    - &macbook age1q352gp8pffm6ku4kqejys50rl4p5padpmedt5fqp5a07s5kr49aswrz0yh
creation_rules:
  - path_regex: home/mario/modules/shell/secrets/*
    key_groups:
    - age:
      - *quietfrost
      - *macbook
      pgp:
      - *mario 
