#+TITLE: Archer-65 Emacs Configuration
#+AUTHOR: Mario Liguori
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes

* Overview and mandatory stuff

This is my personal configuration of ~GNU Emacs~. Many of these settings have been stolen from research and other configurations.
I have a very basic use-case, and this configuration is, currently, pretty straightforward to read.

Right now I'm deprecating =package.el= with =straight.el=, and =leaf.el= is my macro configuration tool.

** Before GUI: "early init"

Is good practice to define an =early-init.el= file: this kind of approach provides better loading for essential stuff.

#+include: "early-init.el" src emacs-lisp :tangle no


** Mandatory settings for the "init"

Note that =init.el= is mandatory, however I'm tangling it from this =.org= file (=Emacs.org=).

#+begin_src emacs-lisp

  ;;; init.el --- Load the full configuration -*- lexical-binding: t -*-
  ;;; Commentary:

  ;; This file bootstraps the configuration, which is divided into
  ;; a number of other files.

  ;;; Code:

  ;; Add load-path
  (add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

  ;; We don't want customizations in `init.el`, instead we use `custom.el`.
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))

  ;; Disable damn sleep!
  ;; Yep, it's mandatory, that's the worst keybind ever.
  (global-unset-key (kbd "C-z"))

#+end_src


* Core settings

** Packages bootstrap

We are requiring =init-packages=, where package manager (e.g. =package.el=, =straight.el=) and macro configuration tools (e.g. =use-package=, =leaf.el=, =setup.el=) are initialized.

#+begin_src emacs-lisp

  ;; Require package management file.
  (require 'init-packages)

#+end_src

This is the =init-packages.el= file.

#+include: "lisp/init-packages.el" src emacs-lisp :tangle no


** Keep order

This useful package helps to avoid filling up our work folders with ~auto-save~ files.

#+begin_src emacs-lisp

  ;; The `no-littering` package to keep folders where we edit files and the Emacs configuration folder clean.
  (leaf no-littering
    :doc "Keeps folders clean"
    :setq
    ;; The package `no-littering` doesn't set this by default so we must place
    ;; auto save files in the same path as it uses for sessions
    (auto-save-file-name-transforms . `((".*" ,(no-littering-expand-var-file-name "auto-save/") t))))
  
#+end_src


** Pick up me mom, I'm scared!

Sometimes we forget shortcuts as we type them, or we wish more _helpful_ description of functions/variables/keys of our environment.

#+begin_src emacs-lisp

  (require 'init-help)

#+end_src

[[https://github.com/justbur/emacs-which-key][Which-Key]] is a minor mode for Emacs that displays the key bindings following your currently entered incomplete command in a popup.

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful information to =describe-= command buffers. For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.

This is the =init-help.el= file, nothing special.

#+include: "lisp/init-help.el" src emacs-lisp :tangle no


** Appearance

#+begin_src emacs-lisp

  (require 'init-appearance)

#+end_src

I'm currently using these: [[https://protesilaos.com/emacs/modus-themes][Modus Themes]]. Protesilaos made a great work, and these themes are, indeed, built into Emacs.
Here are also contained line-numbers settings, modeline (doom atm) related configuration, minor tweaks for icons (needed also for dashboard) and colors.

Here the =init.appearance.el= file.

#+include: "lisp/init-appearance.el" src emacs-lisp :tangle no


** Font

Readability is important.
Currently using [[https://rubjo.github.io/victor-mono/][Victor Mono]] as font, I love it, also for variable-pitch face.

#+begin_src emacs-lisp

  (require 'init-fonts)

#+end_src

Here the =init.fonts.el= file.

#+include: "lisp/init-fonts.el" src emacs-lisp :tangle no


** Dashboard Configuration

Useless cute dashboard, nothing to say, and there are minor tweaks to make it work with server-mode and Emacs PGTK/NativeComp.

#+begin_src emacs-lisp

  (require 'init-dash)

#+end_src

Here the =init-dash.el= file.

#+include: "lisp/init-dash.el" src emacs-lisp :tangle no


* Selection and search

** Monster trio of completion

#+begin_src emacs-lisp

  (require 'init-complete)

#+end_src

As Completion UI [[https://github.com/minad/vertico][Vertico]] is my preferred choice, it's lightweight and fast, and relies on Emacs internals. [[https://github.com/minad/marginalia/][Marginalia]] for rich annotations provides a summary for candidates.
Completion can be better with an [[https://github.com/oantolin/orderless][Orderless]] (similar to FZF, if you know). Orderless is also customizable for matching style.

Following, the =init-complete.el= file.

#+include: "lisp/init-complete.el" src emacs-lisp :tangle no


** Consult

#+begin_src emacs-lisp

  (require 'init-consult)

#+end_src

[[https://github.com/minad/consult][Consult]] provides practical commands based on the Emacs completion function completing-read.

Consult offers, for example:
- Buffer switching command =consult-buffer= to switch between buffers and recently opened files.
- Multiple asynchronous search commands:
  - =consult-grep=
  - =consult-ripgrep=
  - =consult-line=, which resembles [[https://github.com/abo-abo/swiper][Swiper]].

Keybindings and configuration are in the =init-consult.el= file.

#+include: "lisp/init-consult.el" src emacs-lisp :tangle no


** Embark

#+begin_src emacs-lisp

  (require 'init-embark)

#+end_src

[[https://github.com/oantolin/embark/][Embark]] provides contextual menu offering actions for a target determined in the context, exactly like a contextual menu.

Keybindings and configuration are in the =init-embark.el= file.

#+include: "lisp/init-embark.el" src emacs-lisp :tangle no


** Completion at point

#+begin_src emacs-lisp

  (require 'init-complete-in-buffer)

#+end_src

I'm currently using Company, but I've planned to switch on Corfu, especially for child frames instead of overlays.

Here =init-complete-in-buffer.el=.

#+include: "lisp/init-complete-in-buffer.el" src emacs-lisp :tangle no


* Interface interaction


** Editing enhancement

#+begin_src emacs-lisp

  (require 'init-editing)

#+end_src


Tweaks present here:
- Scroll (and smooth scroll for Emacs >= 29);
- Electric-pair mode and show-paren;
- Autorevert files after changes;
- [[https://www.emacswiki.org/emacs/UndoTree][Undo Tree]] mode for simpler undo-redo (and visual branches!).
- Rainbow-mode;
- Delete-selection mode to overwrite selected regions;
- Drag-stuff to...drag stuff around.

#+include: "lisp/init-editing.el" src emacs-lisp :tangle no


** Windows navigation

#+begin_src emacs-lisp

  (require 'init-windows)

#+end_src

Moving around windows can be painful, but some built-in functions save our s**a.

#+include: "lisp/init-windows.el" src emacs-lisp :tangle no


** Meow

#+begin_src emacs-lisp

  ;; (require 'init-meow)

#+end_src

[[https://github.com/meow-edit/meow][Meow]] is yet another modal editing mode for Emacs. Meow aims to blend modal editing into Emacs with minimal interference with its original key-bindings, avoiding most of the hassle introduced by key-binding conflicts.

Keybindings are listed in =init-meow.el=.

#+include: "lisp/init-meow.el" src emacs-lisp :tangle no


* Development

** Projectile

#+begin_src emacs-lisp

  (leaf projectile
    :ensure t
    :blackout t
    :config (projectile-mode)
    :bind-keymap
    ("C-c p"   . projectile-command-map))
    ;;:init
    ;; NOTE: Set this to the folder where you keep your Git repos!
    ;;(when (file-directory-p "~/Git")
    ;;  (setq projectile-project-search-path '("~/Git")))
    ;;(setq projectile-switch-project-action #'projectile-dired))

#+end_src


** Magit

Common Git operations are easy to execute quickly using Magit's command panel system.

#+begin_src emacs-lisp

  (leaf magit
    :commands magit-status
    :custom
    (magit-display-buffer-function . 'magit-display-buffer-same-window-except-diff-v1))

  ;; NOTE: Make sure to configure a GitHub token before using this package!
  ;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
  ;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
  (leaf forge
    :after magit)

#+end_src


** Code style

#+begin_src emacs-lisp

  (require 'init-code-style)

#+end_src

[[https://github.com/glasserc/ethan-wspace][Ethan-wspace]] is a nice package to avoid useless/horrible extra whitespaces.

[[https://github.com/Fanael/rainbow-delimiters][Rainbow-delimiters]] is useful in programming modes because it colorizes nested parentheses and brackets according to their nesting depth.  This makes it a lot easier to visually match parentheses in Emacs Lisp code without having to count them yourself.

The rest of =init-code-style.el= regards tab settings.

#+include: "lisp/init-code-style.el" src emacs-lisp :tangle no


** Syntax checking

Modern on-the-fly syntax checking.

#+begin_src emacs-lisp

  (require 'init-spell-and-check)

#+end_src

I'm a bit distracted, so spell and syntax checking is essential for me.

This is =init-spell-and-check.el=.

#+include: "lisp/init-spell-and-check.el" src emacs-lisp :tangle no


** Extra modes

#+begin_src emacs-lisp

  (require 'init-extra-modes)

#+end_src

=init.extra.modes.el=

#+include: "lisp/init-extra-modes.el" src emacs-lisp :tangle no


** Yasnippet

#+begin_src emacs-lisp

  (require 'init-snippets)

#+end_src

I have to explain this?

Here =init-snippets.el=.

#+include: "lisp/init-snippets.el" src emacs-lisp :tangle no


** LSP

[[https://github.com/emacs-lsp/lsp-mode][Language Server Protocol]] support with multiples languages support for Emacs.


#+begin_src emacs-lisp

  (leaf lsp-mode
    :init
    :config
    (add-to-list 'lsp-language-id-configuration '(nix-mode . "nix"))
    (lsp-register-client
     (make-lsp-client :new-connection (lsp-stdio-connection '("rnix-lsp"))
                      :major-modes '(nix-mode)
                      :server-id 'nix))
    ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
    (setq lsp-keymap-prefix "C-c l")
    :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
           (java-mode . lsp)
           (c-mode . lsp)
           (c++-mode . lsp)
           (haskell-mode-hook . lsp)
           (nix-mode . lsp)
           ;; if you want which-key integration
           (lsp-mode . lsp-enable-which-key-integration))
    :commands lsp)

  ;; optionally if you want to use debugger
  ;; (use-package dap-mode)
  ;; (use-package dap-LANGUAGE) to load the dap adapter for your language

#+end_src

*** LSP-UI

#+begin_src emacs-lisp

  (leaf lsp-treemacs
    :after lsp)

#+end_src

*** C/C++

#+begin_src emacs-lisp

  ;; Already set in LSP, to rewatch a little bit

#+end_src

*** JAVA

#+begin_src emacs-lisp

  (leaf lsp-java
    :config (add-hook 'java-mode-hook 'lsp))

#+end_src


* Org Mode

** Basic Config

This section contains the basic configuration for =org-mode= plus the configuration for Org agendas and capture templates.

#+begin_src emacs-lisp

  (defun archer-65/org-mode-setup ()
    (org-indent-mode)
    (variable-pitch-mode 1)
    (visual-line-mode 1))

  (leaf org
    ;:pin org
    :ensure t
    :require t
    :hook (org-mode-hook . archer-65/org-mode-setup)
    :config
    (setq org-ellipsis " ▾")
    (setq org-pretty-entities 't))

#+end_src

*** Nicer Heading Bullets

[[https://github.com/sabof/org-bullets][org-bullets]] replaces the heading stars in =org-mode= buffers with nicer looking characters that you can control.

#+begin_src emacs-lisp

  (leaf org-modern
    :ensure t
    :require t
    :after org
    :hook (org-mode-hook . org-modern-mode))

#+end_src

*** Center Org Buffers

We use [[https://github.com/joostkremers/visual-fill-column][visual-fill-column]] to center =org-mode= buffers for a more pleasing writing experience as it centers the contents of the buffer horizontally to seem more like you are editing a document.  This is really a matter of personal preference so you can remove the block below if you don't like the behavior.

#+begin_src emacs-lisp

  (defun archer-65/org-mode-visual-fill ()
    (setq visual-fill-column-width 170
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (leaf visual-fill-column
    :hook (org-mode-hook . archer-65/org-mode-visual-fill))

#+end_src

*** Date

#+begin_src emacs-lisp
  
  ;; Date settings for org-mode
  (setq-default org-display-custom-times t)
  (setq org-time-stamp-custom-formats
        '("<%d %b %Y>" . "<%d/%m/%y %a %H:%M>"))
  
#+end_src

** Export LaTeX

#+begin_src emacs-lisp
  
  ;; LaTeX export settings
  (setq org-latex-pdf-process
        '("latexmk -pdflatex='pdflatex -interaction nonstopmode' -pdf -bibtex -f %f"))
  
  (require 'ox-latex)
  (unless (boundp 'org-latex-classes)
    (setq org-latex-classes nil))
  
  ;; Newpage after TOC
  (setq org-latex-toc-command "\\tableofcontents \\clearpage")
  
  ;; Article 
  (add-to-list 'org-latex-classes
               '("article"
                 "\\documentclass[11pt,a4paper]{article}
  \\usepackage[utf8]{inputenc}
  \\usepackage[T1]{fontenc}
  \\usepackage{fixltx2e}
  \\usepackage{graphicx}
  \\usepackage{longtable}
  \\usepackage{float}
  \\usepackage{wrapfig}
  \\usepackage{rotating}
  \\usepackage[normalem]{ulem}
  \\usepackage{amsmath}
  \\usepackage{textcomp}
  \\usepackage{marvosym}
  \\usepackage{wasysym}
  \\usepackage{amssymb}
  \\usepackage{hyperref}
  \\usepackage{mathpazo}
  \\usepackage{color}
  \\usepackage{enumerate}
  \\definecolor{bg}{rgb}{0.95,0.95,0.95}
  \\tolerance=1000
        [NO-DEFAULT-PACKAGES]
        [PACKAGES]
        [EXTRA]
  \\linespread{1.1}
  \\hypersetup{pdfborder=0 0 0}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")))
  
  ;; Using minted for tables
  (setq org-latex-listings 'minted
        org-latex-packages-alist '(("" "minted"))
        org-latex-pdf-process
        '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
          "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
          "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
  
  (setq org-latex-minted-options '(("breaklines" "true")
                                   ("breakanywhere" "true")))
  
#+end_src

** HTML Reveal.js

#+begin_src emacs-lisp
  (leaf ox-reveal
    :ensure ox-reveal)

  (setq org-reveal-root "https://cdn.jsdelivr.net/npm/reveal.js")
#+end_src

** Configure Babel Languages

To execute or export code in =org-mode= code blocks, you'll need to set up =org-babel-load-languages= for each language you'd like to use.  [[https://orgmode.org/worg/org-contrib/babel/languages.html][This page]] documents all of the languages that you can use with =org-babel=.

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    (org-babel-do-load-languages
        'org-babel-load-languages
        '((emacs-lisp . t))))

    (push '("conf-unix" . conf-unix) org-src-lang-modes)

#+end_src

** Structure Templates

Org Mode's [[https://orgmode.org/manual/Structure-Templates.html][structure templates]] feature enables you to quickly insert code blocks into your Org files in combination with =org-tempo= by typing =<= followed by the template name like =el= or =py= and then press =TAB=.  For example, to insert an empty =emacs-lisp= block below, you can type =<el= and press =TAB= to expand into such a block.

You can add more =src= block templates below by copying one of the lines and changing the two strings at the end, the first to be the template name and the second to contain the name of the language [[https://orgmode.org/worg/org-contrib/babel/languages.html][as it is known by Org Babel]].

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    ;; This is needed as of Org 9.2
    (require 'org-tempo)

    (add-to-list 'org-structure-template-alist '("bash" . "src bash"))
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("cc" . "src c")))

#+end_src

** LaTeX Live

This snippet is used to highlight LaTeX code in org files

#+begin_src emacs-lisp

  (eval-after-load 'org
    '(setf org-highlight-latex-and-related '(latex)))

#+end_src

** Auto-tangle Configuration Files

This snippet adds a hook to =org-mode= buffers so that =archer-65/org-babel-tangle-config= gets executed each time such a buffer gets saved.  This function checks to see if the file being saved is the Emacs.org file you're looking at right now, and if so, automatically exports the configuration here to the associated output files.

#+begin_src emacs-lisp

  ;; Automatically tangle our Emacs.org config file when we save it.
  (defun archer-65/org-babel-tangle-config ()
    (when (string-equal (file-name-directory (buffer-file-name))
                        (expand-file-name archer--config-path))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'archer-65/org-babel-tangle-config)))

#+end_src

* File Management

** Dired

Dired is a built-in file manager for Emacs that does some pretty amazing things!  Here are some key bindings you should try out:

*** Key Bindings

**** Navigation

- =n= - next line
- =p= - previous line
- =j= - jump to file in buffer
- =RET= - select file or directory
- =^= - go to parent directory
- =S-RET= - Open file in "other" window
- =M-RET= - Show file in other window without focusing (previewing files)
- =g o= (=dired-view-file=) - Open file but in a "preview" mode, close with =q=
- =g= - Refresh the buffer with =revert-buffer= after changing configuration (and after filesystem changes!)

**** Marking files

- =m= - Marks a file
- =u= - Unmarks a file
- =U= - Unmarks all files in buffer
- ='*' t= - Inverts marked files in buffer
- =% m= - Mark files in buffer using regular expression
- =*= - Lots of other auto-marking functions
- =k= - "Kill" marked items (refresh buffer with =g= / =g r= to get them back)
- Many operations can be done on a single file if there are no active marks!

**** Copying and Renaming files

- =C= - Copy marked files (or if no files are marked, the current file)
- Copying single and multiple files
- =U= - Unmark all files in buffer
- =R= - Rename marked files, renaming multiple is a move!
- =% R= - Rename based on regular expression: =^test= , =old-\&=

*Power command*: =C-x C-q= (=dired-toggle-read-only=) - Makes all file names in the buffer editable directly to rename them!  Press =Z Z= to confirm renaming or =Z Q= to abort.

**** Deleting files

- =D= - Delete marked file
- =d= - Mark file for deletion
- =x= - Execute deletion for marks
- =delete-by-moving-to-trash= - Move to trash instead of deleting permanently

**** Creating and extracting archives

- =Z= - Compress or uncompress a file or folder to (=.tar.gz=)
- =c= - Compress selection to a specific file
- =dired-compress-files-alist= - Bind compression commands to file extension

**** Other common operations

- =T= - Touch (change timestamp)
- =M= - Change file mode
- =O= - Change file owner
- =G= - Change file group
- =S= - Create a symbolic link to this file
- =L= - Load an Emacs Lisp file into Emacs

*** Configuration

#+begin_src emacs-lisp

  (leaf dired
    :ensure nil
    :commands (dired dired-jump)
    :bind ("C-x C-j" . dired-jump)
    :custom
    (dired-listing-switches . "-agho --group-directories-first")
    :hook
    (dired-load-hook . (lambda () (interactive) (dired-collapse))))


  ;; (put 'dired-find-alternate-file 'disabled nil)

  ;; (add-hook 'dired-mode-hook
  ;;           (lambda ()
  ;;             (define-key dired-mode-map (kbd "<return>")
  ;;                         'dired-find-alternate-file) ; was dired-advertised-find-file
  ;;             (define-key dired-mode-map (kbd "^")
  ;;                         (lambda () (interactive) (find-alternate-file "..")))
  ;;                                         ; was dired-up-directory
  ;;             ))

  (leaf dired-single
    :commands (dired dired-jump))

  (leaf all-the-icons-dired
    :hook (dired-mode-hook . all-the-icons-dired-mode))

  (leaf dired-hide-dotfiles
    :hook (dired-mode-hook . dired-hide-dotfiles-mode)
    :config
    (define-key dired-mode-map (kbd "C-c d") 'dired-hide-dotfiles-mode))

#+end_src

* Mail

** MU4E

#+begin_src emacs-lisp

  (leaf emojify
    :hook (after-init . global-emojify-mode))

  (leaf mu4e
    :load-path "/usr/share/emacs/site-lisp/mu4e/"
    :require t
    :config

    ;; Use mu4e for sending e-mail
    (setq mail-user-agent 'mu4e-user-agent)

    (setq sendmail-program "/usr/bin/msmtp"
      message-sendmail-f-is-evil t
      message-sendmail-extra-arguments '("--read-envelope-from")
      send-mail-function 'smtpmail-send-it
      message-send-mail-function 'message-send-mail-with-sendmail)
      ;mu4e-compose-signature "Sent from Emacs")

    (with-eval-after-load "emojify"
      (delete 'mu4e-headers-mode emojify-inhibit-major-modes))

    (require 'mu4e-contrib)

    (setq shr-color-visible-luminance-min 60)
    (setq shr-color-visible-distance-min 5)
    (setq shr-use-colors nil)
    (advice-add #'shr-colorize-region :around (defun shr-no-colourise-region (&rest ignore)))

    ;; Load org-mode integration
    (require 'org-mu4e)

    ;; This is set to 't' to avoid mail syncing issues when using mbsync
    (setq mu4e-change-filenames-when-moving t)

    ;; Refresh mail using isync every 10 minutes
    (setq mu4e-get-mail-command "mbsync -a")
    (setq mu4e-update-interval (* 5 60))
    (setq mu4e-maildir "~/mails")
    (setq mu4e-main-buffer-hide-personal-addresses t)

    (setq mu4e-contexts
          (list
           ;; Gmail Account
           (make-mu4e-context
            :name "Gmail"
            :match-func
            (lambda (msg)
              (when msg
                (string-prefix-p "/Gmail" (mu4e-message-field msg :maildir))))
            :vars '((mu4e-sent-folder  . "/Gmail/[Gmail]/Sent Mail")
                    (mu4e-drafts-folder  . "/Gmail/[Gmail]/Drafts")
                    (mu4e-trash-folder  . "/Gmail/[Gmail]/Trash")
                    (mu4e-maildir-shortcuts .
                                            (("/Gmail/Inbox"     . ?i)
                                             ("/Gmail/[Gmail]/Sent Mail" . ?s)
                                             ("/Gmail/[Gmail]/Trash"     . ?t)
                                             ("/Gmail/[Gmail]/Drafts"    . ?d)))))
           ;; Outlook
           (make-mu4e-context
            :name "Outlook"
            :match-func
            (lambda (msg)
              (when msg
                (string-prefix-p "/Outlook" (mu4e-message-field msg :maildir))))
            :vars '((mu4e-drafts-folder  . "/Outlook/Drafts")
                    (mu4e-sent-folder  . "/Outlook/Sent")
                    (mu4e-refile-folder  . "/Outlook/Archive")
                    (mu4e-trash-folder  . "/Outlook/Deleted")
                    (mu4e-maildir-shortcuts .
                                            (("/Outlook/Inbox"   . ?i)
                                             ("/Outlook/Sent"    . ?s)
                                             ("/Outlook/Deleted" . ?t)
                                             ("/Outlook/Drafts"  . ?d)))))

           ;;UniNa
           (make-mu4e-context
            :name "Unina"
            :match-func
            (lambda (msg)
              (when msg
                (string-prefix-p "/Unina" (mu4e-message-field msg :maildir))))
            :vars '((mu4e-drafts-folder  . "/Unina/Bozze")
                    (mu4e-sent-folder  . "/Unina/Posta inviata")
                    (mu4e-trash-folder  . "/Unina/Deleted Items")
                    (mu4e-maildir-shortcuts .
                                            (("/Unina/Inbox"         . ?i)
                                             ("/Unina/Posta inviata" . ?s)
                                             ("/Unina/Deleted Items" . ?t)
                                             ("/Unina/Bozze"         . ?d)))))))
    ;; Set Bookmarks for all
    (setq  mu4e-bookmarks '(( :name  "Unread messages"
                              :query "flag:unread AND NOT flag:trashed"
                              :key ?u)
                            ( :name "Today's messages"
                              :query "date:today..now"
                              :key ?t)))

    (setq mu4e-context-policy 'pick-first)

    ;; don't keep message buffers around
    (setq message-kill-buffer-on-exit t)

    ;; Don't ask to quit... why is this the default?
    (setq mu4e-confirm-quit nil)
    (mu4e t))

#+end_src

** MUE4-ALERT

#+begin_src emacs-lisp

  (leaf mu4e-alert
    :after mu4e
    :init
    (mu4e-alert-set-default-style 'libnotify)

    (add-hook 'after-init-hook #'mu4e-alert-enable-notifications)

    (defun mu4e-alert--get-mu4e-frame ()
      "Try getting a frame containing a mu4e buffer."
      (car (delq nil (mapcar (lambda (buffer)
                               (when (and buffer
                                          (get-buffer-window buffer t))
                                 (window-frame (get-buffer-window buffer t))))
                             (list mu4e-main-buffer-name)))))

    (defun mu4e-alert-filter-repeated-mails (mails)
      "Filters the MAILS that have been seen already."
      (cl-remove-if (lambda (mail)
                      (prog1 (and (not mu4e-alert-notify-repeated-mails)
                                  (ht-get mu4e-alert-repeated-mails
                                          (plist-get mail :message-id)))
                        (ht-set! mu4e-alert-repeated-mails
                                 (plist-get mail :message-id)
                                 t)))
                    mails))

    (setq mu4e-alert-notify-repeated-mails nil))

#+end_src

** Org Mail

#+begin_src emacs-lisp

  (leaf org-msg
    :after mu4e
    :config
    (setq org-msg-options "html-postamble:nil H:5 num:nil ^:{} toc:nil author:nil email:nil \\n:t"
          org-msg-startup "hidestars indent inlineimages"
          org-msg-default-alternatives '((new		. (text html))
                                         (reply-to-html	. (text html))
                                         (reply-to-text	. (text)))
          org-msg-convert-citation t)
    (org-msg-mode))

#+end_srcx
